fix segment,callin,http doc incorrect description
shenruisi/salyut_doc pull request #7
Opened 2020-05-28 12:44 UTC by leewenchen

2020-05-29 02:29 UTC, shenruisi commented on docs/http.md
> +|   url   | [string](datatype.md)  | √ |  发起网络请求的目标地址，可以是http或https开头 |
This type should be expr

2020-05-29 02:30 UTC, shenruisi commented on docs/http.md
> +|   media   | [string](datatype.md)  | x  |  post数据的媒体类型，默认为`text/plain`,可参考[MIME类型](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Basics_of_HTTP/MIME_types) |
This type should be expr

2020-05-29 02:48 UTC, shenruisi commented on docs/http.md
> +- http: {url: '"http://127.0.0.1/formPost"', media: '"application/x-www-form-urlencoded"', post: '"content=hello"', path: '/resp'}
Try to get a reachable url to give the examples.
Maybe like that

- http: {url: '"https://reqbin.com/echo/post/form"', media: '"application/x-www-form-urlencoded"', post: '"content=hello"', path: '/resp'}
- echo: '$/resp'

2020-05-29 02:50 UTC, shenruisi requested changes
Try to update with suggestions.

2020-05-31 16:50 UTC, shenruisi commented on docs/callin.md
> +|   package   | [string](datatype.md)  | √ |   |
This type should be expr

2020-05-31 16:51 UTC, shenruisi commented on docs/callin.md
> +|   seg   | [string](datatype.md)  | √ |   |
This type should be expr

2020-05-31 16:51 UTC, shenruisi commented on docs/callin.md
> +|   0...49   | [string](datatype.md) | x  |   |
This type should be expr

2020-05-31 16:52 UTC, shenruisi requested changes
Try to update with suggestions.

2020-06-01 06:26 UTC, Turbe commented on docs/segment.md
>        - return: '$/z'
adjust indent, preferred 4 spaces

2020-06-01 07:58 UTC, leewenchen commented on docs/segment.md
>        - return: '$/z'
got it

2020-06-01 08:22 UTC, merged